-- Automated 48-hour party payment reminders are handled by the send-party-final-reminder Edge Function.
-- To enable automation, schedule this function via the Supabase dashboard (pg_cron) or an external cron job.
-- Example cron expression: 0 * * * * (hourly)
-- The cron job should call: POST https://<project>.supabase.co/functions/v1/send-party-final-reminder
-- with an Authorization header and optionally a list of bookings that need reminders.
--
-- Manual admin trigger is also available in the admin dashboard booking drawer.
